#!/bin/sh
### BEGIN INIT INFO
# Provides:       mavproxy_startup
# Required-Start: $network $remote_fs $syslog
# Required-Stop:  $network $remote_fs $syslog
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Description:    MavProxy
### END INIT INFO

sleep 10
cd /home/pi/Desktop/mavproxy
# /usr/local/bin/mavproxy.py --master=/dev/serial0 --baudrate 921600 --out 192.168.168.200:14550 --daemon > test_log 2>test_err &
/usr/local/bin/mavproxy.py --master=/dev/ttyPixhawk --baudrate 921600 --out 192.168.168.200:14550 --daemon > test_log 2>test_err &

exit 0
