#!/bin/bash
### BEGIN INIT INFO
# Provides:       pymavlink_startup
# Required-Start: $network $remote_fs $syslog
# Required-Stop:  $network $remote_fs $syslog
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Description:    pymavlink
### END INIT INFO

sudo pigpiod
sleep 5
export MAVLINK20="1"
cd /home/pi/Desktop/GACompanionComp/log/

/home/pi/Desktop/companionComp/bin/python3 /home/pi/Desktop/GACompanionComp/pymavlink_main.py --vehicle GA3A --fileLog &

exit 0
